### ISSUE TITLE
SQL error after installing plugin

### ISSUE THREAD

**Issue by olivermarshall2** [poctob/OSTEquipmentPlugin#41] opened 2015-11-03 12:46 UTC
After installing the plugin, we see all the entries in the osTicket staff portal but we get a great big error at the top of the page. Any ideas how to resolve it?

[ALTER TABLE `ost_equipment` CHANGE COLUMN `name` `asset_id` VARCHAR(255) NOT NULL , ADD COLUMN `staff_id` INT NULL AFTER `is_active`, ADD COLUMN `user_id` INT NULL AFTER `staff_id` DROP INDEX `name`] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP INDEX `name`' at line 5[CREATE PROCEDURE `ost_CreateEquipmentFormFields`() BEGIN SET @form_id = (SELECT id FROM `ost_form` WHERE title='Equipment' LIMIT 1); SET @status_list_id = (SELECT id FROM `ost_list` WHERE `name`='equipment_status' LIMIT 1); SET @equipment_list_id = (SELECT id FROM `ost_list` WHERE `name`='equipment' LIMIT 1); IF (@form_id IS NOT NULL) AND (@status_list_id IS NOT NULL) AND (@equipment_list_id IS NOT NULL) then INSERT INTO `ost_form_field` (`form_id`, `type`, `label`, `required`, `private`, `edit_mask`, `name`, `sort`, `created`, `updated`) VALUES (@form_id, CONCAT('list-',@equipment_list_id), 'Equipment', 0,0,0, 'equipment',    3,  NOW(), NOW());  INSERT INTO `ost_form_field` (`form_id`, `type`, `label`, `required`, `private`, `edit_mask`, `name`, `sort`, `created`, `updated`) VALUES (@form_id, CONCAT('list-',@status_list_id), 'Status', 0,0,0, 'status',   2,  NOW(), NOW());  INSERT INTO `ost_form_field` (`form_id`, `type`, `label`, `required`, `private`, `edit_mask`, `name`, `sort`, `created`, `updated`) VALUES (@form_id, ('text'), 'Asset ID', 0,0,0, 'asset_id',  1,  NOW(), NOW());  END IF; END] PROCEDURE ost_CreateEquipmentFormFields already exists
Error parsing SQL schema! Get help from developers (#4)
Upgrade configuration error. Unable to upgrade database tables!

**Comment by poctob** [comment] 2015-11-03 13:41
Seems to be a duplicate of 
https://github.com/poctob/OSTEquipmentPlugin/issues/38

Please see if solution there works for you.

**Comment by olivermarshall2** [comment] 2015-11-03 13:53
If I run the SQL statement at the end of that post it does remove the error. However it also removes the plugin. 

If I re-install and re-enable the plugin then the error comes back.

Olly

**Comment by poctob** [comment] 2015-11-03 14:07
Are you using the upstream version?

**Comment by olivermarshall2** [comment] 2015-11-03 14:10
Errr just downloaded it today from 
https://github.com/poctob/OSTEquipmentPlugin

**Comment by poctob** [comment] 2015-11-03 14:13
Not from here: https://github.com/poctob/OSTEquipmentPlugin/releases though?

**Comment by olivermarshall2** [comment] 2015-11-03 14:48
Just created a blank osTicket install and installed the plugin from the /releases link. 

I get the same error. 

Oddly the ALTER statement that is mentioned in the error appears to have been actioned, in that I have the columns it would create, set to the correct settings, and with the name column dropped. 

Olly

**Comment by poctob** [comment] 2015-11-03 14:51
OK.  Do not install from releases link, download upstream version from here: 
https://github.com/poctob/OSTEquipmentPlugin/archive/master.zip

, do fresh install and let me know if the problem is still there.  SQL error may appear immediately after the install, but should go away on navigating away from the page.

**Comment by olivermarshall2** [comment] 2015-11-03 15:02
Same thing. As soon as I hit the Agent Panel button to go to the agent panel, the message appears and stays there.

Olly

**Comment by poctob** [comment] 2015-11-03 15:14
What's the version of MySQL and OSTicket Core

**Comment by olivermarshall2** [comment] 2015-11-03 15:17
MySQL 5.5.45
osTicket-v1.9.12

**Comment by poctob** [comment] 2015-11-03 15:20
OK.  MySQL is outdated, see
https://github.com/poctob/OSTEquipmentPlugin/issues/35

**Comment by poctob** [comment] 2016-01-16 17:12
closing for lack or activity

**Closed as completed by poctob** 2016-01-16 17:12 UTC
